# Generated by Django 4.2 on 2023-04-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=100, verbose_name='Nome do aluno')),
                ('nome_livro', models.CharField(max_length=100, verbose_name='Nome do livro')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor do livro')),
                ('ano', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ano de publicação')),
                ('data_emprestimo', models.CharField(max_length=16, verbose_name='Data de empréstimo')),
                ('data_devol', models.CharField(max_length=16, verbose_name='Data de devolução')),
            ],
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='sobrenome',
            new_name='sobrename',
        ),
    ]
