# Generated by Django 4.2 on 2023-04-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emprestimo_rename_nome_aluno_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devol',
            field=models.DateField(verbose_name='Data de devolução'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateTimeField(verbose_name='Data de empréstimo'),
        ),
    ]
