# Generated by Django 4.2 on 2023-04-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_emprestimo_data_devol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_book', models.CharField(max_length=100, verbose_name='Nome do Livro')),
                ('aut', models.CharField(max_length=100, verbose_name='Nome do autor')),
                ('editora', models.CharField(max_length=100, verbose_name='Editora')),
                ('ano', models.IntegerField(verbose_name='Ano de publicação')),
            ],
        ),
    ]
