# Generated by Django 4.2 on 2023-04-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_catalogacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
