# Generated by Django 4.2 on 2023-04-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_produto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
