# Generated by Django 4.2 on 2023-04-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='sobrename',
            new_name='sobrenome',
        ),
    ]
