# Generated by Django 4.2 on 2023-05-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_name_aluno_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogacao',
            name='usuarios',
            field=models.ManyToManyField(related_name='livros', to='core.aluno'),
        ),
    ]
