# Generated by Django 4.2 on 2023-05-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_catalogacao_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogacao',
            name='usuarios',
        ),
    ]
